service: pogocard

provider:
  name: aws
  runtime: nodejs8.10
  memorySize: 128
  timeout: 9
  stage: dev
  profile: personal-dev
  region: us-east-1
  cfLogs: true

package:
  individually: true

functions:
  profile:
    handler: profile.image
    description: generate pogocard
    events:
      - http:
          path: /profile-card
          method: get
          cors: true

